#:kivy 2.1.0

<AnswerButton>:
    font_size:"22sp"
    color: [0, 0, 0, 1]
    on_press: self.onPress(self)
    on_release: self.onRelease(self)
    text_size: self.size
    halign: "center"
    valign: "middle"

<PopUpButton>:
    font_size:25
    color: [0, 0, 0, 1]
    text_size: self.size
    halign: "center"
    valign: "middle"

<CaptionLabel>:
    font_name: "Comic"
    text_size: self.size